export const htmlSuggestions = [
  { label: "div", snippet: "<div>$1</div>" },
  { label: "span", snippet: "<span>$1</span>" },
  { label: "p", snippet: "<p>$1</p>" },
  { label: "h1", snippet: "<h1>$1</h1>" },
  { label: "h2", snippet: "<h2>$1</h2>" },
  { label: "h3", snippet: "<h3>$1</h3>" },
  { label: "h4", snippet: "<h4>$1</h4>" },
  { label: "h5", snippet: "<h5>$1</h5>" },
  { label: "h6", snippet: "<h6>$1</h6>" },
  { label: "a", snippet: '<a href="$1">$2</a>' },
  { label: "img", snippet: '<img src="$1" alt="$2">' },
  { label: "ul", snippet: "<ul>\n\t<li>$1</li>\n</ul>" },
  { label: "ol", snippet: "<ol>\n\t<li>$1</li>\n</ol>" },
  { label: "li", snippet: "<li>$1</li>" },
  {
    label: "table",
    snippet: "<table>\n\t<tr>\n\t\t<td>$1</td>\n\t</tr>\n</table>",
  },
  { label: "tr", snippet: "<tr>\n\t<td>$1</td>\n</tr>" },
  { label: "td", snippet: "<td>$1</td>" },
];

export const cssSuggestions = [
  { label: "width", snippet: "width: $1;" },
  { label: "height", snippet: "height: $1;" },
  { label: "background-color", snippet: "background-color: $1;" },
  { label: "color", snippet: "color: $1;" },
  { label: "font-size", snippet: "font-size: $1;" },
  { label: "font-weight", snippet: "font-weight: $1;" },
  { label: "text-align", snippet: "text-align: $1;" },
  { label: "border", snippet: "border: $1;" },
  { label: "padding", snippet: "padding: $1;" },
  { label: "margin", snippet: "margin: $1;" },
  { label: "display", snippet: "display: $1;" },
  { label: "flex-direction", snippet: "flex-direction: $1;" },
  { label: "justify-content", snippet: "justify-content: $1;" },
  { label: "align-items", snippet: "align-items: $1;" },
  { label: "position", snippet: "position: $1;" },
  { label: "top", snippet: "top: $1;" },
  { label: "right", snippet: "right: $1;" },
  { label: "bottom", snippet: "bottom: $1;" },
  { label: "left", snippet: "left: $1;" },
  { label: "z-index", snippet: "z-index: $1;" },
  { label: "opacity", snippet: "opacity: $1;" },
  { label: "border-radius", snippet: "border-radius: $1;" },
  { label: "transition", snippet: "transition: $1;" },
];
