export const htmlSuggestions = [
  { label: "div", snippet: "<div>$1</div>" },
  { label: "span", snippet: "<span>$1</span>" },
  { label: "p", snippet: "<p>$1</p>" },
  { label: "h1", snippet: "<h1>$1</h1>" },
  { label: "h2", snippet: "<h2>$1</h2>" },
  { label: "h3", snippet: "<h3>$1</h3>" },
  { label: "h4", snippet: "<h4>$1</h4>" },
  { label: "h5", snippet: "<h5>$1</h5>" },
  { label: "h6", snippet: "<h6>$1</h6>" },
  { label: "a", snippet: '<a href="$1">$2</a>' },
  { label: "img", snippet: '<img src="$1" alt="$2">' },
  { label: "ul", snippet: "<ul>\n\t<li>$1</li>\n</ul>" },
  { label: "ol", snippet: "<ol>\n\t<li>$1</li>\n</ol>" },
  { label: "li", snippet: "<li>$1</li>" },
  {
    label: "table",
    snippet: "<table>\n\t<tr>\n\t\t<td>$1</td>\n\t</tr>\n</table>",
  },
  { label: "tr", snippet: "<tr>\n\t<td>$1</td>\n</tr>" },
  { label: "td", snippet: "<td>$1</td>" },
  { label: "form", snippet: '<form action="$1" method="$2">\n\t$3\n</form>' },
  { label: "input", snippet: '<input type="$1" name="$2" value="$3">' },
  { label: "button", snippet: "<button>$1</button>" },
  { label: "label", snippet: '<label for="$1">$2</label>' },
  { label: "textarea", snippet: '<textarea name="$1">$2</textarea>' },
  {
    label: "select",
    snippet: '<select name="$1">\n\t<option value="$2">$3</option>\n</select>',
  },
  { label: "option", snippet: '<option value="$1">$2</option>' },
  { label: "header", snippet: "<header>$1</header>" },
  { label: "footer", snippet: "<footer>$1</footer>" },
  { label: "nav", snippet: "<nav>$1</nav>" },
  { label: "section", snippet: "<section>$1</section>" },
  { label: "article", snippet: "<article>$1</article>" },
  { label: "aside", snippet: "<aside>$1</aside>" },
  { label: "main", snippet: "<main>$1</main>" },
  { label: "head", snippet: "<head>$1</head>" },
  { label: "body", snippet: "<body>$1</body>" },
  { label: "meta", snippet: '<meta name="$1" content="$2">' },
  { label: "link", snippet: '<link rel="$1" href="$2">' },
  {
    label: "fieldset",
    snippet: "<fieldset>\n\t<legend>$1</legend>\n\t$2\n</fieldset>",
  },
  { label: "legend", snippet: "<legend>$1</legend>" },
  { label: "video", snippet: '<video src="$1" controls>$2</video>' },
  { label: "audio", snippet: '<audio src="$1" controls>$2</audio>' },
  { label: "source", snippet: '<source src="$1" type="$2">' },
  {
    label: "iframe",
    snippet: '<iframe src="$1" frameborder="0" allowfullscreen>$2</iframe>',
  },
  { label: "canvas", snippet: '<canvas width="$1" height="$2"></canvas>' },
  { label: "div[id]", snippet: '<div id="$1">$2</div>' },
  { label: "div[class]", snippet: '<div class="$1">$2</div>' },
  { label: "span[id]", snippet: '<span id="$1">$2</span>' },
  { label: "span[class]", snippet: '<span class="$1">$2</span>' },
  { label: "img[srcset]", snippet: '<img srcset="$1" alt="$2">' },
  { label: "img[width]", snippet: '<img src="$1" alt="$2" width="$3">' },
  { label: "img[height]", snippet: '<img src="$1" alt="$2" height="$3">' },
  { label: "a[target]", snippet: '<a href="$1" target="$2">$3</a>' },
  { label: "a[rel]", snippet: '<a href="$1" rel="$2">$3</a>' },
  { label: "a[download]", snippet: '<a href="$1" download>$2</a>' },
  { label: "ul[style]", snippet: '<ul style="$1">\n\t<li>$2</li>\n</ul>' },
  { label: "ol[start]", snippet: '<ol start="$1">\n\t<li>$2</li>\n</ol>' },
  { label: "li[value]", snippet: '<li value="$1">$2</li>' },
  {
    label: "table[border]",
    snippet: '<table border="$1">\n\t<tr>\n\t\t<td>$2</td>\n\t</tr>\n</table>',
  },
  { label: "tr[bgcolor]", snippet: '<tr bgcolor="$1">\n\t<td>$2</td>\n</tr>' },
  { label: "td[colspan]", snippet: '<td colspan="$1">$2</td>' },
];
export const cssSuggestions = [
  { label: "width", snippet: "width: $1;" },
  { label: "height", snippet: "height: $1;" },
  { label: "background-color", snippet: "background-color: $1;" },
  { label: "color", snippet: "color: $1;" },
  { label: "font-size", snippet: "font-size: $1;" },
  { label: "font-weight", snippet: "font-weight: $1;" },
  { label: "text-align", snippet: "text-align: $1;" },
  { label: "border", snippet: "border: $1;" },
  { label: "padding", snippet: "padding: $1;" },
  { label: "margin", snippet: "margin: $1;" },
  { label: "display", snippet: "display: $1;" },
  { label: "flex-direction", snippet: "flex-direction: $1;" },
  { label: "justify-content", snippet: "justify-content: $1;" },
  { label: "align-items", snippet: "align-items: $1;" },
  { label: "position", snippet: "position: $1;" },
  { label: "top", snippet: "top: $1;" },
  { label: "right", snippet: "right: $1;" },
  { label: "bottom", snippet: "bottom: $1;" },
  { label: "left", snippet: "left: $1;" },
  { label: "z-index", snippet: "z-index: $1;" },
  { label: "opacity", snippet: "opacity: $1;" },
  { label: "border-radius", snippet: "border-radius: $1;" },
  { label: "transition", snippet: "transition: $1;" },
  { label: "text-decoration", snippet: "text-decoration: $1;" },
  { label: "text-transform", snippet: "text-transform: $1;" },
  { label: "line-height", snippet: "line-height: $1;" },
  { label: "box-sizing", snippet: "box-sizing: $1;" },
  { label: "float", snippet: "float: $1;" },
  { label: "clear", snippet: "clear: $1;" },
  { label: "overflow", snippet: "overflow: $1;" },
  { label: "text-overflow", snippet: "text-overflow: $1;" },
  { label: "white-space", snippet: "white-space: $1;" },
  { label: "font-family", snippet: "font-family: $1;" },
  { label: "font-style", snippet: "font-style: $1;" },
  { label: "letter-spacing", snippet: "letter-spacing: $1;" },
  { label: "word-spacing", snippet: "word-spacing: $1;" },
  { label: "text-indent", snippet: "text-indent: $1;" },
  { label: "vertical-align", snippet: "vertical-align: $1;" },
  { label: "list-style-type", snippet: "list-style-type: $1;" },
  { label: "list-style-image", snippet: "list-style-image: $1;" },
  { label: "list-style-position", snippet: "list-style-position: $1;" },
  { label: "box-shadow", snippet: "box-shadow: $1;" },
  { label: "text-shadow", snippet: "text-shadow: $1;" },
  { label: "cursor", snippet: "cursor: $1;" },
  { label: "background-image", snippet: "background-image: $1;" },
  { label: "background-position", snippet: "background-position: $1;" },
  { label: "background-repeat", snippet: "background-repeat: $1;" },
  { label: "background-size", snippet: "background-size: $1;" },
  { label: "background-attachment", snippet: "background-attachment: $1;" },
  { label: "background-origin", snippet: "background-origin: $1;" },
  { label: "background-clip", snippet: "background-clip: $1;" },
  { label: "outline", snippet: "outline: $1;" },
  { label: "outline-color", snippet: "outline-color: $1;" },
  { label: "outline-style", snippet: "outline-style: $1;" },
  { label: "outline-width", snippet: "outline-width: $1;" },
  { label: "box-decoration-break", snippet: "box-decoration-break: $1;" },
  { label: "text-justify", snippet: "text-justify: $1;" },
  { label: "text-shadow", snippet: "text-shadow: $1;" },
  { label: "text-overflow", snippet: "text-overflow: $1;" },
  { label: "text-align-last", snippet: "text-align-last: $1;" },
  { label: "hyphens", snippet: "hyphens: $1;" },
  { label: "columns", snippet: "columns: $1;" },
  { label: "column-count", snippet: "column-count: $1;" },
  { label: "column-width", snippet: "column-width: $1;" },
  { label: "column-gap", snippet: "column-gap: $1;" },
  { label: "break-inside", snippet: "break-inside: $1;" },
  { label: "break-after", snippet: "break-after: $1;" },
  { label: "break-before", snippet: "break-before: $1;" },
  { label: "page-break-inside", snippet: "page-break-inside: $1;" },
  { label: "page-break-after", snippet: "page-break-after: $1;" },
  { label: "page-break-before", snippet: "page-break-before: $1;" },
  { label: "overflow-x", snippet: "overflow-x: $1;" },
  { label: "overflow-y", snippet: "overflow-y: $1;" },
  { label: "pointer-events", snippet: "pointer-events: $1;" },
  { label: "user-select", snippet: "user-select: $1;" },
  { label: "resize", snippet: "resize: $1;" },
  { label: "object-fit", snippet: "object-fit: $1;" },
  { label: "object-position", snippet: "object-position: $1;" },
  { label: "will-change", snippet: "will-change: $1;" },
  { label: "backface-visibility", snippet: "backface-visibility: $1;" },
  { label: "perspective", snippet: "perspective: $1;" },
  { label: "perspective-origin", snippet: "perspective-origin: $1;" },
  { label: "transform", snippet: "transform: $1;" },
  { label: "transform-origin", snippet: "transform-origin: $1;" },
  { label: "transition-property", snippet: "transition-property: $1;" },
  { label: "transition-duration", snippet: "transition-duration: $1;" },
  { label: "transition-timing-function", snippet: "transition-timing-function: $1;" },
  { label: "transition-delay", snippet: "transition-delay: $1;" },
];
